name: tdmpc2
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pytorch
  - torchvision
  - cudatoolkit=11.7
  - glew
  - glib
  - pip==21
  - pip:
    - absl-py
    - glfw
    - kornia
    - termcolor
    - gym==0.21.0
    - moviepy
    - ffmpeg
    - imageio
    - imageio-ffmpeg
    - omegaconf
    - hydra-core
    - hydra-submitit-launcher
    - submitit
    - patchelf
    - protobuf
    - tqdm
    - transforms3d
    - joblib
    - opencv-python
    - opencv-contrib-python
    - filelock
    - sapien==2.2.1
    - mani-skill2==0.4.1
    - trimesh
    - open3d
    - setuptools==65.5.0
    - "cython<3"
    - mujoco==2.3.1
    - mujoco-py==2.1.2.14
    - dm-control
    - pillow
    - pyquaternion
    - git+https://github.com/Farama-Foundation/Metaworld.git@04be337a12305e393c0caf0cbf5ec7755c7c8feb
    # - myosuite # MyoSuite requires gym==0.13.0 which conflicts with Meta-World & ManiSkill2, install separately if needed
    - tensordict-nightly
    - torchrl-nightly
    - wandb
